# .github/workflows/deploy.yml
name: FastAPI Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Simplified condition

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SSH into EC2 and Deploy
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${EC2_IP} << 'EOF'
            cd /home/ubuntu/app || exit 1

            # Pull the latest code from GitHub
            git pull origin main || exit 1

            # Stop & remove the old container if it exists
            sudo docker stop fastapi-nginx || exit 1
            sudo docker rm fastapi-nginx || exit 1

            sudo docker build -t fastapi-nginx -f /home/ubuntu/app/Dockerfile . || exit 1

            # Run the new container (expose ports for future HTTPS setup)
            sudo docker run -d -p 80:80 --name fastapi-nginx fastapi-nginx:latest || exit 1
            sleep 1
            # Verify Deployment (Optional)
            curl -i 127.0.0.1:80/healthcheck
          EOF

      - name: Clean up SSH Key
        if: always()
        run: rm -f private_key

